### ISSUE TITLE
Развитие проекта

### ISSUE THREAD

**Issue by kiple** [JewishCoder/MetaEditor#1]
## Задание до 22.06.2017
1. Привести формат xml-файла к виду:
```
<?xml version="1.0" encoding="utf-8"?>
<Image>
    <Version Value="1.0" />
    <Brightness Value="Light/Dark" />
    <Description Value="Трасса" />
    <Plates>
        <Plate>
            <Number Value="A234EM35" />
            <Stencil Value="RU_N01_a000aa00" />
            <Zone>
                <Point X="300" Y="100" />
                <Point X="420" Y="100" />
                <Point X="420" Y="120" />
                <Point X="300" Y="120" />
            </Zone>
            <Quality Value="low/normal/high" />
        </Plate>
        <Plate>
            <Number Value="23-ABC-4" />
            <Stencil Value="NL_N01_00aaa0" />
            <Zone>
                <Point X="20" Y="100" />
                <Point X="150" Y="100" />
                <Point X="150" Y="120" />
                <Point X="20" Y="120" />
            </Zone>
            <Quality Value="Low/Normal/High" />
        </Plate>
    </Plates>
</Image>
```
2. Создать классы `ImageMetadata` и `PlateMetadata` с методами `SaveXml()` и `LoadXml()`.
3. Объединить проект с библиотечными классами в один.
4. При сохранение строки номера в xml он должен конвертироваться в Latin Upper. Использовать `string.ToUpper()` и класс `Dictionary<TK, TV>`.

**Comment by JewishCoder** [comment]
Насчет шаблонов, Вы их попозже скинете или уже в понедельник?

**Comment by kiple** [comment]
Файл с шаблонами [stencils.txt](https://github.com/JewishCoder/Cshapr/files/1100026/stencils.txt).

**Comment by kiple** [comment]
Сделать к 28.06.2017

1. Сохранение настроек программы. Файл с настройками должен формироваться автоматически. Настройки: путь к папке с изображениями, положение формы и т.п.
2. Переименовать название ПО: имя проекта, имя файлов и заголовок.
3. Изменит механизм добавления/удаления и редактирования номера: кнопки _Добавть/Удалить_.
4. Добавить защиту от потери данных: спрашивать пользователя о необходимости сохранять метаданные изображения и номера.
5. Добавить файл с шаблонами в проект.

**Comment by kiple** [comment]
Иван, Никита, я попытался добавить вывод рамки на изображение автомобиля, и столкнулся с проблемой: похоже наша архитектура зашла в тупик :) Предлагаю сделать следующим образом: я отрефакторю ПО на верхнем уровне - напишу, где что-нужно сделать и сделаю тесты, а с вас нижний уровень.

**Comment by kiple** [comment]
Сделайте, пожалуйста, веткой по умолчанию - ветку **master**. Это делается в настройках репозитория  - у меня нет прав.

**Comment by JewishCoder** [comment]
Я сделал ветку по умолчанию master

**Comment by kiple** [comment]
Ок. Я сейчас в код буду писать специальные комментарии в формате `TODO:`, в которых укажу, что нужно будет сделать. В Visual Studio эти комментарии можно посмотреть в окне `View/Task List`.

**Comment by JewishCoder** [comment]
Насчет завтра, стоит приходить? или делать доработки?

**Comment by kiple** [comment]
Лучше подойти, обсудим более подробно, что нужно сделать.

**Comment by kiple** [comment]
Изменен xml-формат файла с метаданными:
```
<?xml version="1.0" encoding="utf-8"?>
<Image Version="1.0">
	<HumanChecked Value="false" />
	<Brightness Value="Light/Dark" />
	<Description Value="Трасса" />
	<Plates>
		<Plate>
			<Number Value="A234EM35" />
			<Stencil Value="RU_N01_a000aa00" />
			<Zone>
				<Point X="300" Y="100" />
				<Point X="420" Y="100" />
				<Point X="420" Y="120" />
				<Point X="300" Y="120" />
			</Zone>
			<Quality Value="Low/Normal/High" />
		</Plate>
		<Plate>
			<Number Value="23-ABC-4" />
			<Stencil Value="NL_N01_00aaa0" />
			<Zone>
				<Point X="20" Y="100" />
				<Point X="150" Y="100" />
				<Point X="150" Y="120" />
				<Point X="20" Y="120" />
			</Zone>
			<Quality Value="Low/Normal/High" />
		</Plate>
	</Plates>
</Image>
```

**Comment by kiple** [comment]
Проект переведен под MS Framework .NET 4.7. Если в VS нет поддержки данного версии FW, то нужно поставить отсюда https://www.microsoft.com/en-us/download/details.aspx?id=55168.

**Comment by kiple** [comment]
Сохранение и загрузку метаданных из xml я сделал - так как эти классы мне нужны для автоматической разметки файлов.

**Comment by kiple** [comment]
Иван, добавьте Веснина Е.Н. в проект: VesninEN / jvesnin@gmail.com

**Comment by JewishCoder** [comment]
У меня такой вопросик, методы, которые в MainForm нужно переносить в отдельный класс?
