### ISSUE TITLE
Статистика по количеству номеров разных стран/шаблонов

### ISSUE THREAD

**Issue by VesninEN** [JewishCoder/MetaEditor#12]
Нужна для того чтобы понять каких примеров у нас нет или мало и что нужно размечать в первую очередь
отображать:
Число изображений
Число размеченных изображений

В дальнейшим расширить информацию с учетом (день/ночь), качество изображения, размер номера

**Comment by VesninEN** [comment]
1. Добавить столбец с числом изображений в папке
2. Отображать полный путь в тултипе
3. Переход к папке при нажатии на название директории

**Comment by VesninEN** [comment]
4. В окне статистики сделать выбор папки
5. Сделать подробную статистику по выбранной папке. Основное назначение статистики - понять какие данные у нас есть, каких данных не хватает.
Статистика должна содержать информацию по:

- кол-во изображений и разметки (подтвержденное и нет) каждого типа номера (каждая страна имеет несколько типов номеров)
- кол-во изображений и разметки день/ночь
- изображений и разметки с номерами разных размеров
--Ширина номера до 10% от ширины кадра
--Ширина номера от 10% до 30% от ширины кадра
--Ширина номера более 30% от ширины кадра
- кол-во изображений и разметки с разным качетвом изображений

**Comment by VesninEN** [comment]
М.б. реализовать это с возможностью экспорта данных (изображения+разметка), удовлетворяющих выбранным критериям

**Comment by JewishCoder** [comment]
1,3,4 - сделано

**Comment by VesninEN** [comment]
Отображать кол-во изображений всесто кол-ва изображений с разметкой

**Comment by VesninEN** [comment]
Подробная информация об использовании оперативной 
(JIT) отладки вместо данного диалогового 
окна содержится в конце этого сообщения.

************** Текст исключения **************
System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в Recar2.MetaEditor.Statistics._dgrvStatistics_RowStateChanged(Object sender, DataGridViewRowStateChangedEventArgs e) в C:\Users\Иван\Source\Repos\Cshapr2\MetaEditor.prj\Statistics.cs:строка 70
   в System.Windows.Forms.DataGridView.OnRowStateChanged(Int32 rowIndex, DataGridViewRowStateChangedEventArgs e)
   в System.Windows.Forms.DataGridView.OnDataGridViewElementStateChanged(DataGridViewElement element, Int32 index, DataGridViewElementStates elementState)
   в System.Windows.Forms.DataGridViewBand.OnStateChanged(DataGridViewElementStates elementState)
   в System.Windows.Forms.DataGridViewBand.set_DisplayedInternal(Boolean value)
   в System.Windows.Forms.DataGridViewRowCollection.SetRowState(Int32 rowIndex, DataGridViewElementStates state, Boolean value)
   в System.Windows.Forms.DataGridView.FlushDisplayedChanged()
   в System.Windows.Forms.DataGridView.PerformLayoutPrivate(Boolean useRowShortcut, Boolean computeVisibleRows, Boolean invalidInAdjustFillingColumns, Boolean repositionEditingControl)
   в System.Windows.Forms.DataGridView.ResetUIState(Boolean useRowShortcut, Boolean computeVisibleRows)
   в System.Windows.Forms.DataGridViewRowCollection.OnCollectionChanged_PreNotification(CollectionChangeAction cca, Int32 rowIndex, Int32 rowCount, DataGridViewRow& dataGridViewRow, Boolean changeIsInsertion)
   в System.Windows.Forms.DataGridViewRowCollection.OnCollectionChanged(CollectionChangeEventArgs e, Int32 rowIndex, Int32 rowCount, Boolean changeIsDeletion, Boolean changeIsInsertion, Boolean recreateNewRow, Point newCurrentCell)
   в System.Windows.Forms.DataGridViewRowCollection.InsertInternal(Int32 rowIndex, DataGridViewRow dataGridViewRow, Boolean force)
   в System.Windows.Forms.DataGridViewRowCollection.InsertInternal(Int32 rowIndex, DataGridViewRow dataGridViewRow)
   в System.Windows.Forms.DataGridViewRowCollection.Insert(Int32 rowIndex, DataGridViewRow dataGridViewRow)
   в System.Windows.Forms.DataGridViewRowCollection.AddInternal(Boolean newRow, Object[] values)
   в System.Windows.Forms.DataGridViewRowCollection.Add(Object[] values)
   в Recar2.MetaEditor.Statistics._lblSelectDirectory_LinkClicked(Object sender, LinkLabelLinkClickedEventArgs e) в C:\Users\Иван\Source\Repos\Cshapr2\MetaEditor.prj\Statistics.cs:строка 51
   в System.Windows.Forms.LinkLabel.OnLinkClicked(LinkLabelLinkClickedEventArgs e)
   в System.Windows.Forms.LinkLabel.OnMouseUp(MouseEventArgs e)
   в System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   в System.Windows.Forms.Control.WndProc(Message& m)
   в System.Windows.Forms.Label.WndProc(Message& m)
   в System.Windows.Forms.LinkLabel.WndProc(Message& msg)
   в System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   в System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   в System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Загруженные сборки **************
mscorlib
    Версия сборки: 4.0.0.0
    Версия Win32: 4.7.2053.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
recar2.metaeditor
    Версия сборки: 0.4.0.0
    Версия Win32: 0.4.0.0
    CodeBase: file:///D:/%D0%9C%D0%B0%D0%BB%D0%BB%D0%B5%D0%BD%D0%BE%D0%BC%20%D0%A1%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D1%81_Yandex%D0%94%D0%B8%D1%81%D0%BA/%D0%9C%D0%B0%D0%BB%D0%BB%D0%B5%D0%BD%D0%BE%D0%BC%20%D0%A1%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D1%81/2017/!%D0%90%D0%9C.%D0%A0%D0%B0%D0%B7%D0%B2%D0%B8%D1%82%D0%B8%D0%B5/%D0%A3%D1%82%D0%B8%D0%BB%D0%B8%D1%82%D0%B0%20%D0%B4%D0%BB%D1%8F%20%D1%80%D0%B0%D0%B7%D0%BC%D0%B5%D1%82%D0%BA%D0%B8%20%D1%81%D1%82%D0%BE%D0%BF-%D0%BA%D0%B0%D0%B4%D1%80%D0%BE%D0%B2%20%D0%90%D0%9C/recar2.metaeditor.0.4.1.0/Release/recar2.metaeditor.exe
----------------------------------------
System.Windows.Forms
    Версия сборки: 4.0.0.0
    Версия Win32: 4.7.2053.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Версия сборки: 4.0.0.0
    Версия Win32: 4.7.2053.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Версия сборки: 4.0.0.0
    Версия Win32: 4.7.2053.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
recar2.metaeditor.classes
    Версия сборки: 1.0.0.0
    Версия Win32: 1.0.0.0
    CodeBase: file:///D:/%D0%9C%D0%B0%D0%BB%D0%BB%D0%B5%D0%BD%D0%BE%D0%BC%20%D0%A1%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D1%81_Yandex%D0%94%D0%B8%D1%81%D0%BA/%D0%9C%D0%B0%D0%BB%D0%BB%D0%B5%D0%BD%D0%BE%D0%BC%20%D0%A1%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D1%81/2017/!%D0%90%D0%9C.%D0%A0%D0%B0%D0%B7%D0%B2%D0%B8%D1%82%D0%B8%D0%B5/%D0%A3%D1%82%D0%B8%D0%BB%D0%B8%D1%82%D0%B0%20%D0%B4%D0%BB%D1%8F%20%D1%80%D0%B0%D0%B7%D0%BC%D0%B5%D1%82%D0%BA%D0%B8%20%D1%81%D1%82%D0%BE%D0%BF-%D0%BA%D0%B0%D0%B4%D1%80%D0%BE%D0%B2%20%D0%90%D0%9C/recar2.metaeditor.0.4.1.0/Release/recar2.metaeditor.classes.DLL
----------------------------------------
mallenom.imaging
    Версия сборки: 3.6.7.431
    Версия Win32: 3.6.7.431
    CodeBase: file:///D:/%D0%9C%D0%B0%D0%BB%D0%BB%D0%B5%D0%BD%D0%BE%D0%BC%20%D0%A1%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D1%81_Yandex%D0%94%D0%B8%D1%81%D0%BA/%D0%9C%D0%B0%D0%BB%D0%BB%D0%B5%D0%BD%D0%BE%D0%BC%20%D0%A1%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D1%81/2017/!%D0%90%D0%9C.%D0%A0%D0%B0%D0%B7%D0%B2%D0%B8%D1%82%D0%B8%D0%B5/%D0%A3%D1%82%D0%B8%D0%BB%D0%B8%D1%82%D0%B0%20%D0%B4%D0%BB%D1%8F%20%D1%80%D0%B0%D0%B7%D0%BC%D0%B5%D1%82%D0%BA%D0%B8%20%D1%81%D1%82%D0%BE%D0%BF-%D0%BA%D0%B0%D0%B4%D1%80%D0%BE%D0%B2%20%D0%90%D0%9C/recar2.metaeditor.0.4.1.0/Release/mallenom.imaging.DLL
----------------------------------------
mallenom.framework
    Версия сборки: 2.7.6.211
    Версия Win32: 2.7.6.211
    CodeBase: file:///D:/%D0%9C%D0%B0%D0%BB%D0%BB%D0%B5%D0%BD%D0%BE%D0%BC%20%D0%A1%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D1%81_Yandex%D0%94%D0%B8%D1%81%D0%BA/%D0%9C%D0%B0%D0%BB%D0%BB%D0%B5%D0%BD%D0%BE%D0%BC%20%D0%A1%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D1%81/2017/!%D0%90%D0%9C.%D0%A0%D0%B0%D0%B7%D0%B2%D0%B8%D1%82%D0%B8%D0%B5/%D0%A3%D1%82%D0%B8%D0%BB%D0%B8%D1%82%D0%B0%20%D0%B4%D0%BB%D1%8F%20%D1%80%D0%B0%D0%B7%D0%BC%D0%B5%D1%82%D0%BA%D0%B8%20%D1%81%D1%82%D0%BE%D0%BF-%D0%BA%D0%B0%D0%B4%D1%80%D0%BE%D0%B2%20%D0%90%D0%9C/recar2.metaeditor.0.4.1.0/Release/mallenom.framework.DLL
----------------------------------------
System.Configuration
    Версия сборки: 4.0.0.0
    Версия Win32: 4.7.2053.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Версия сборки: 4.0.0.0
    Версия Win32: 4.7.2053.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Версия сборки: 4.0.0.0
    Версия Win32: 4.7.2053.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Версия сборки: 4.0.0.0
    Версия Win32: 4.7.2053.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Windows.Forms.resources
    Версия сборки: 4.0.0.0
    Версия Win32: 4.7.2053.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_ru_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
mscorlib.resources
    Версия сборки: 4.0.0.0
    Версия Win32: 4.7.2053.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_ru_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------

************** Оперативная отладка (JIT) **************
Для подключения оперативной (JIT) отладки файл .config данного
приложения или компьютера (machine.config) должен иметь
значение jitDebugging, установленное в секции system.windows.forms.
Приложение также должно быть скомпилировано с включенной
отладкой.

Например:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

При включенной отладке JIT любое необрабатываемое исключение
пересылается отладчику JIT, зарегистрированному на данном компьютере,
вместо того чтобы обрабатываться данным диалоговым окном.
